# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProveedor', models.CharField(max_length=30)),
                ('telefonoProveedor', models.IntegerField()),
                ('direccionProveedor', models.CharField(max_length=100)),
                ('tipoProveedor', models.CharField(max_length=1)),
                ('emailProveedor', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
