# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 23:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('diuCliente', models.IntegerField()),
                ('direccionCliente', models.IntegerField()),
                ('tipoCliente', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoContrato', models.CharField(max_length=30)),
                ('fechaContrato', models.DateField()),
                ('duracionContrato', models.CharField(max_length=15)),
                ('fechaInicio', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('horaEntrada', models.DateTimeField()),
                ('horaSalida', models.DateTimeField()),
                ('salario', models.FloatField()),
                ('vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDepartamento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('duiEmpleado', models.IntegerField()),
                ('nitEmpleado', models.IntegerField()),
                ('isssEmpleado', models.IntegerField()),
                ('afpEmpleado', models.IntegerField()),
                ('codigoEmpleado', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=30)),
                ('funcion', models.CharField(max_length=500)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Departamento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Empleado'),
        ),
    ]
