# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puesto',
            options={'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
    ]
