# Generated by Django 2.0.6 on 2018-09-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField()),
                ('Cotizacion', models.IntegerField()),
                ('Valor_total', models.FloatField()),
                ('Cant_productos', models.IntegerField()),
                ('Deposito', models.FloatField()),
                ('Fecha', models.DateField()),
                ('Num_seguimiento', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=10)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
    ]
