# Generated by Django 2.0.6 on 2018-09-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Cliente',
        ),
    ]
