# Generated by Django 2.0.6 on 2018-09-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0003_pedido_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente',
            new_name='Cliente',
        ),
    ]
