# Generated by Django 2.0.6 on 2018-09-14 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0001_initial'),
        ('Pedido', '0005_auto_20180913_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.Cotizacion')),
            ],
            options={
                'verbose_name': 'LineaPedido',
                'verbose_name_plural': 'LineaPedidos',
            },
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Numero',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Cotizacion',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='Pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.Pedido'),
        ),
    ]
