# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecotizacion',
            name='archivo',
            field=models.FileField(null=True, upload_to='uploads/%Y-%m-%d/%H_%M_%S'),
        ),
    ]
