# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0002_auto_20180910_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='detalle',
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='Cotizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotizacion.Cotizacion'),
            preserve_default=False,
        ),
    ]
