# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_auto_20180912_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descripcion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
