# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0004_cotizacion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(max_length=25)),
                ('cantidad', models.FloatField()),
                ('tipoCliente', models.CharField(max_length=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.TipoProducto')),
            ],
        ),
    ]
