# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0005_precioproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamanioProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='precioproducto',
            name='tamaño',
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='tamanio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotizacion.TamanioProducto'),
            preserve_default=False,
        ),
    ]
