# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0006_auto_20180912_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamanioproducto',
            name='descripcio',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
