# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0007_tamanioproducto_descripcio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tamanioproducto',
            old_name='descripcio',
            new_name='descripcion',
        ),
    ]
