# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0008_auto_20180912_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproducto',
            name='precio',
        ),
        migrations.AlterField(
            model_name='precioproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
