# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0009_auto_20180912_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioproducto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='precioproducto',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
