# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0010_auto_20180912_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioproducto',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
