# Generated by Django 2.0.6 on 2018-09-18 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0011_precioproducto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='material',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='tamaño',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotizacion.PrecioProducto'),
            preserve_default=False,
        ),
    ]
