# Generated by Django 2.0.6 on 2018-09-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogoproductos',
            name='precioUnitario',
        ),
    ]
