# Generated by Django 2.0.6 on 2018-09-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='Fecha',
            new_name='fecha',
        ),
    ]
